-- # TRIGGERS # -- 
-- USE INVENTORY;

CREATE TRIGGER TR_IN_OR 
ON ORDERS 
FOR INSERT 
AS 
BEGIN
	SET NOCOUNT ON;
	DECLARE @OQ AS INT;
	DECLARE @SQ AS INT;

	SET @OQ = (SELECT OQTY FROM INSERTED);
	SET @SQ = (SELECT SQTY FROM STOCK WHERE PID = (SELECT PID FROM INSERTED));

	IF @SQ >= @OQ 
		BEGIN 
			UPDATE STOCK SET SQTY = SQTY - @OQ
			WHERE PID = (SELECT PID FROM INSERTED);

			COMMIT;
			PRINT('ORDER ACCEPTED  ')

		END ;
	ELSE 
		BEGIN
			ROLLBACK;
			PRINT('ORDER REJECTED AS INSUFFICIENT STOCK');
		END;
END;



CREATE TRIGGER TR_UP_OR
ON ORDERS
FOR UPDATE
AS
BEGIN
		SET NOCOUNT ON;
		DECLARE @OQ AS INT;
		DECLARE @NQ AS INT; 

		SET @OQ = (SELECT OQTY FROM DELECTED); 
		SET @NQ = (SELECT OQTY FROM INSERTED);

		UPDATE STOCK SET SQTY = SQTY + (@OQ - @NQ)
		WHERE PID = (SELECT PID FROM INSERTED)

END;
